### ISSUE TITLE
Decoding error on Windows

### ISSUE THREAD

**Issue by tomkoenecke** [dlesbre/bibtex-autocomplete#3]
Hi,

Originially coming from "the stackexchange post", I ran into this error with the bare script there, where it struggles to open (and write) one of my .bib files. Adding `encoding="utf8"` to the `with open(...)` (and `write()`) fixed it in the script.

The same error appears with this package  on **Windows**, it works fine with the package out of the box on the same .bib file on a Linux VM, however.

This is the error message:

```
Reading file 1 / 1 from 'References.bib'
Traceback (most recent call last):
  File "...user\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "...user\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "...user\AppData\Local\Programs\Python\Python39\lib\site-packages\bibtexautocomplete\__main__.py", line 4, in <module>
    main()
  File "...user\AppData\Local\Programs\Python\Python39\lib\site-packages\bibtexautocomplete\core\main.py", line 73, in main
    databases = BibtexAutocomplete.read(args.input)
  File "...user\AppData\Local\Programs\Python\Python39\lib\site-packages\bibtexautocomplete\core\autocomplete.py", line 273, in read
    dbs.append(file_read(file))
  File "...user\AppData\Local\Programs\Python\Python39\lib\site-packages\bibtexautocomplete\bibtex\io.py", line 72, in file_read
    bibtex = file.read()
  File "...user\AppData\Local\Programs\Python\Python39\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 8540: character maps to <undefined>
```

Really like the project you have going on here. It did return a couple of false entries and inaccuracies, but is overall a really convenient tool.

Tom

**Comment by dlesbre** [comment]
Thanks for the bug report ! I'll upload a new version with the suggested changes.

If you're willing to share some of the entries where you found incorrect data/false matches I might be able to refine the match detection or add data sanity checks.
